schemas:
  - alias: "integration"
    namespace: "http://www.springframework.org/schema/integration"
    location: "http://localhost:8080/spring-integration-5.2.xsd"
    excludedElements:
      - "selector-chain"
      - "spel-property-accessors"
      - "converter"
      - "chain"
  - alias: "jms"
    namespace: "http://www.springframework.org/schema/integration/jms"
    location: "http://localhost:8080/spring-integration-jms-5.2.xsd"

importedSchemaLocations:
  - namespace: "http://www.springframework.org/schema/beans"
    location: "http://localhost:8080/spring-beans.xsd"
  - namespace: "http://www.springframework.org/schema/tool"
    location: "http://localhost:8080/spring-tool.xsd"